POST http://localhost:8080/
Accept: */*
Cache-Control: no-cache

{
  "urls": [
    "https://jsonplaceholder.typicode.com/posts/1",
    "https://jsonplaceholder.typicode.com/posts/2",
    "https://jsonplaceholder.typicode.com/posts/3",
    "https://jsonplaceholder.typicode.com/posts/4",
    "https://jsonplaceholder.typicode.com/posts/5",
    "https://jsonplaceholder.typicode.com/posts/6",
    "https://jsonplaceholder.typicode.com/posts/7",
    "https://jsonplaceholder.typicode.com/posts/8",
    "https://jsonplaceholder.typicode.com/posts/9",
    "https://jsonplaceholder.typicode.com/posts/10",
    "https://jsonplaceholder.typicode.com/posts/11",
    "https://jsonplaceholder.typicode.com/posts/12",
    "https://error.error",
    "https://jsonplaceholder.typicode.com/posts/14",
    "https://jsonplaceholder.typicode.com/posts/15",
    "https://jsonplaceholder.typicode.com/posts/16",
    "https://jsonplaceholder.typicode.com/posts/17",
    "https://jsonplaceholder.typicode.com/posts/18",
    "https://jsonplaceholder.typicode.com/posts/19",
    "https://jsonplaceholder.typicode.com/posts/20"
  ]
}

###
